"""create users leads internship applications

Revision ID: a585b3e151bb
Revises: 
Create Date: 2026-10-10 15:15:17.642675

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a585b3e151bb'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('internship_applications',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('education', sa.String(length=200), nullable=False),
    sa.Column('institute', sa.String(length=200), nullable=False),
    sa.Column('skills', sa.Text(), nullable=False),
    sa.Column('experience_level', sa.String(length=50), nullable=False),
    sa.Column('track', sa.String(length=100), nullable=False),
    sa.Column('github_url', sa.String(length=300), nullable=True),
    sa.Column('linkedin_url', sa.String(length=300), nullable=True),
    sa.Column('portfolio_url', sa.String(length=300), nullable=True),
    sa.Column('cv_path', sa.String(length=500), nullable=True),
    sa.Column('previous_projects', sa.Text(), nullable=True),
    sa.Column('availability', sa.String(length=200), nullable=True),
    sa.Column('preferred_area', sa.String(length=200), nullable=True),
    sa.Column('motivation', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('applicant', 'under_review', 'shortlisted', 'interview', 'selected', 'active', 'completed', 'rejected', name='applicationstatus', native_enum=False, length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_internship_applications_email'), 'internship_applications', ['email'], unique=False)
    op.create_table('leads',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('company', sa.String(length=200), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('service_interest', sa.String(length=100), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('new', 'contacted', 'qualified', 'client', 'lost', name='leadstatus', native_enum=False, length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leads_email'), 'leads', ['email'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('founder', 'admin', 'intern', 'client', name='userrole', native_enum=False, length=30), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_leads_email'), table_name='leads')
    op.drop_table('leads')
    op.drop_index(op.f('ix_internship_applications_email'), table_name='internship_applications')
    op.drop_table('internship_applications')
    # ### end Alembic commands ###
